### ISSUE TITLE
EasyInstaller Closes

### ISSUE THREAD

**Issue by bns34** [Kyiro/Fortnite-ManifestsArchive#14]
As soon as I open EasyInstaller, it closes with a bunch of SSL handshake errors. Ive tried disabling AV + Firewall but nothing helps

**Comment by Kyiro** [comment]
Do you have Fiddler or some proxy opened?

**Comment by bns34** [comment]
> Do you have Fiddler or some proxy opened?

Oh sorry for being so dumb but ye, now that I think about it, I'm pretty sure I had Fiddler open at the time 😂
