### ISSUE TITLE
Explain this lmao

### ISSUE THREAD

**Issue by Sotarnicus** [Kyiro/Fortnite-ManifestsArchive#7]
![image](https://user-images.githubusercontent.com/77815370/105430017-8bc4b280-5c8d-11eb-8f8b-2f9da69b55c0.png)

I played on rift yesterday watching the galactus and travis scott events, i get on today, after a full shutdown of my computer so the file couldn't possibly still be running, i load up epic and then go into fortnite, the file somehow OPENS ITSELF and windows defender says it's a trojan. It's almost as if it tried to steal my login? 

Explain lmaoooo

**Comment by Kyiro** [comment]
It's literally open source lol

**Comment by Kyiro** [comment]
not an expert on anti viruses but it's probably caused beacuse EasyInstaller writes to disk and is compiled in pyinstaller which Windows Defender can't recognize
